name: Report
description: Sends a Pushover notification to user based on status of pipeline run.

inputs:
  success:
    description: True/False if success run.
    required: true
  repo_name: 
    description: Name of the repo that the pipeline is running for.
    required: true
  pushover_user:
    description: User key for Pushover notification system.
    required: true
  pushover_token:
    description: App token for Pushover notification system.
    required: true
  development:
    description: True/False if this is development environment.
    default: false

runs:
  using: composite
  steps:
    - name: Get Meta
      id: meta
      run: |
        echo DATE_RELEASE=$(echo "`date +'%Y.%m.%d'`") >> $GITHUB_OUTPUT
        echo ENDING_TAG=${{ development && '-dev' || '' }}

    - name: Pipeline Success
      if: inputs.success
      uses: umahmood/pushover-actions@main
      env:
        PUSHOVER_USER: ${{ inputs.pushover_user }}
        PUSHOVER_TOKEN: ${{ inputs.pushover_token }}
      with:
        title: Gitea DevOps
        message: ✅ Built & Pushed ${{ inputs.repo_name }}:${{ steps.meta.outputs.DATE_RELEASE }}${{ steps.meta.outputs.IMAGE_TAG_ENDING }} app!

    - name: Pipeline Failure
      if: ${{ !inputs.success }}
      uses: umahmood/pushover-actions@main
      env:
        PUSHOVER_USER: ${{ inputs.pushover_user }}
        PUSHOVER_TOKEN: ${{ inputs.pushover_token }}
      with:
        title: Gitea DevOps
        message: ❌ Unable to build & push ${{ inputs.repo_name }}:${{ steps.meta.outputs.DATE_RELEASE }}${{ steps.meta.outputs.IMAGE_TAG_ENDING }} app.
