name: Report
description: Sends a Pushover notification to user based on status of pipeline run.

inputs:
  success:
    description: True/False if success run.
    required: true
  development:
    description: True/False if this is development environment.
    default: false
  pushover_user:
    description: User key for Pushover notification system.
    required: true
  pushover_token:
    description: App token for Pushover notification system.
    required: true

runs:
  using: composite
  steps:
    - name: Get Meta
      continue-on-error: true
      id: meta
      run: |
        echo REPO_NAME=$(echo "${GITHUB_REPOSITORY##*/}") >> $GITHUB_OUTPUT
        echo DATE_RELEASE=$(echo "`date +'%Y.%m.%d'`") >> $GITHUB_OUTPUT

    - name: Pipeline Success
      continue-on-error: true
      if: inputs.success
      uses: umahmood/pushover-actions@main
      env:
        PUSHOVER_USER: ${{ inputs.pushover_user }}
        PUSHOVER_TOKEN: ${{ inputs.pushover_token }}
      with:
        title: Gitea DevOps
        message: ✅ Built & Pushed ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}${{ inputs.development && '-dev' || '' }} app!

    - name: Pipeline Failure
      continue-on-error: true
      if: ${{ !inputs.success }}
      uses: umahmood/pushover-actions@main
      env:
        PUSHOVER_USER: ${{ inputs.pushover_user }}
        PUSHOVER_TOKEN: ${{ inputs.pushover_token }}
      with:
        title: Gitea DevOps
        message: ❌ Unable to build & push ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}${{ inputs.development && '-dev' || '' }} app.
